// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreClear.Api.Data;

#nullable disable

namespace backend.Migrations.Auto
{
    [DbContext(typeof(PreclearDbContext))]
    [Migration("20251222085907_AddPricingTotalColumn")]
    partial class AddPricingTotalColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PreClear.Api.Models.BrokerProfile", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("DestinationCountriesJson")
                        .HasColumnType("json")
                        .HasColumnName("destination_countries");

                    b.Property<string>("HsCategoriesJson")
                        .HasColumnType("json")
                        .HasColumnName("hs_categories");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("language");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("license_number");

                    b.Property<int>("MaxConcurrentShipments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("max_concurrent_shipments");

                    b.Property<string>("OriginCountriesJson")
                        .HasColumnType("json")
                        .HasColumnName("origin_countries");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("UserId");

                    b.ToTable("broker_profiles", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.BrokerReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<long?>("BrokerId")
                        .HasColumnType("bigint")
                        .HasColumnName("broker_id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<string>("RequestedDocumentsJson")
                        .HasColumnType("json")
                        .HasColumnName("requested_documents");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("reviewed_at");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("idx_brokerreviews_broker");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_brokerreviews_shipment");

                    b.ToTable("broker_reviews", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long?>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_notifications_shipment");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_notifications_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.Shipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AiApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ai_approval_status");

                    b.Property<decimal?>("AiComplianceScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ai_compliance_score");

                    b.Property<long?>("AssignedBrokerId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_broker_id");

                    b.Property<string>("BrokerApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("broker_approval_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<decimal?>("CustomsValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("customs_value");

                    b.Property<DateTime?>("EstimatedDropoffDate")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("estimated_dropoff_date");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("pickup_date");

                    b.Property<string>("PickupLocation")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("pickup_location");

                    b.Property<string>("PickupTimeEarliest")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pickup_time_earliest");

                    b.Property<string>("PickupTimeLatest")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pickup_time_latest");

                    b.Property<string>("PickupType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pickup_type");

                    b.Property<string>("PreclearToken")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("preclear_token");

                    b.Property<decimal?>("PricingTotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pricing_total");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ServiceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("service_level");

                    b.Property<string>("ShipmentName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("shipment_name");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("shipment_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TokenGeneratedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("token_generated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBrokerId")
                        .HasDatabaseName("idx_shipments_assigned_broker");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_shipments_created_by");

                    b.HasIndex("Mode")
                        .HasDatabaseName("idx_shipments_mode");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("idx_shipments_reference");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_shipments_status");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentCompliance", b =>
                {
                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<bool>("DangerousGoods")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("dangerous_goods");

                    b.Property<decimal?>("EstimatedDuty")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_duty");

                    b.Property<decimal?>("EstimatedTax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_tax");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("evaluated_at");

                    b.Property<bool>("ExportLicenseRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("export_license_required");

                    b.Property<bool>("FoodPharmaFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("food_pharma_flag");

                    b.Property<bool>("LithiumBattery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("lithium_battery");

                    b.Property<string>("MissingDocumentsJson")
                        .HasColumnType("json")
                        .HasColumnName("missing_documents");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<string>("RequiredDocumentsJson")
                        .HasColumnType("json")
                        .HasColumnName("required_documents");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("risk_level");

                    b.Property<string>("SuggestedHsCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("suggested_hs_code");

                    b.HasKey("ShipmentId");

                    b.ToTable("shipment_compliance", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("mime_type");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.Property<decimal?>("ValidationConfidence")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("validation_confidence");

                    b.Property<string>("ValidationNotesJson")
                        .HasColumnType("json")
                        .HasColumnName("validation_notes");

                    b.Property<string>("ValidationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_documents_shipment");

                    b.HasIndex("UploadedBy");

                    b.ToTable("shipment_documents", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("idx_msgs_sender");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_msgs_shipment");

                    b.ToTable("shipment_messages", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("DimensionUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dimension_unit");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("height");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("length");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("package_type");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<bool>("Stackable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("stackable");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("weight");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("weight_unit");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_packages_shipment");

                    b.ToTable("shipment_packages", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address_1");

                    b.Property<string>("Address2")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address_2");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("party_type");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("postal_code");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<string>("State")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("state");

                    b.Property<string>("TaxId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_parties_shipment");

                    b.ToTable("shipment_parties", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExportReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Sale")
                        .HasColumnName("export_reason");

                    b.Property<string>("HsCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("hs_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("name");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("origin_country");

                    b.Property<long>("PackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_id");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_value");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pcs")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("HsCode")
                        .HasDatabaseName("idx_products_hscode");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("idx_products_package");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_products_shipment");

                    b.ToTable("shipment_products", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipperProfile", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address_line_2");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyRole")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("company_role");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("US")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("en")
                        .HasColumnName("language");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("state");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("America/New_York")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("shipper_profiles", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("json")
                        .HasColumnName("metadata");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<bool>("TosAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("tos_accepted");

                    b.Property<DateTime?>("TosAcceptedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tos_accepted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("verification_token");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_users_active");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PreClear.Api.Models.BrokerProfile", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", "User")
                        .WithOne("BrokerProfile")
                        .HasForeignKey("PreClear.Api.Models.BrokerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreClear.Api.Models.BrokerReview", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PreClear.Api.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.Notification", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PreClear.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreClear.Api.Models.Shipment", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", "AssignedBroker")
                        .WithMany()
                        .HasForeignKey("AssignedBrokerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_shipments_users_assigned_broker");

                    b.HasOne("PreClear.Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_shipments_users_created_by");

                    b.Navigation("AssignedBroker");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentCompliance", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", "Shipment")
                        .WithOne("Compliance")
                        .HasForeignKey("PreClear.Api.Models.ShipmentCompliance", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentDocument", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", "Shipment")
                        .WithMany("Documents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreClear.Api.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Shipment");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentMessage", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreClear.Api.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentPackage", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", "Shipment")
                        .WithMany("Packages")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentParty", b =>
                {
                    b.HasOne("PreClear.Api.Models.Shipment", "Shipment")
                        .WithMany("Parties")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentProduct", b =>
                {
                    b.HasOne("PreClear.Api.Models.ShipmentPackage", "Package")
                        .WithMany("Products")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreClear.Api.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipperProfile", b =>
                {
                    b.HasOne("PreClear.Api.Models.User", "User")
                        .WithOne("ShipperProfile")
                        .HasForeignKey("PreClear.Api.Models.ShipperProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreClear.Api.Models.Shipment", b =>
                {
                    b.Navigation("Compliance");

                    b.Navigation("Documents");

                    b.Navigation("Packages");

                    b.Navigation("Parties");
                });

            modelBuilder.Entity("PreClear.Api.Models.ShipmentPackage", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PreClear.Api.Models.User", b =>
                {
                    b.Navigation("BrokerProfile");

                    b.Navigation("ShipperProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
